version: "3"
services:
  nginx:
    image: nginx:1.13.12
    ports:
      - "80:80"
    volumes:
      - ${PWD}/docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/docker/conf/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - esnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - esnet
    volumes:
      - ${PWD}/docker/data/elasticsearch/data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports:
      - "5601:5601"
    networks:
      - esnet
  logstash:
    build: docker/conf/logstash
    image: registry.cn-beijing.aliyuncs.com/wangdali/logstash-syslog
    ports:
      - "5000:5000"
      - "5140:5140"
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
     - ${PWD}/docker/conf/logstash/conf.d:/etc/logstash/conf.d
     - ${PWD}/docker/conf/logstash/patterns:/etc/logstash/patterns
    networks:
      - esnet
networks:
  esnet: